apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: <PATH to the predifined volume>
    server: <NFS server FQDN>
    readOnly: false
  claimRef:
    name: image-registry-storage
    namespace: openshift-image-registry
